game:
  default-required-flags: 4
  default-win-seconds: 60
  neutral-flag-material: GLASS
  build-block-count: 128
  flag-block-count: 64

  # Team building blocks can be placed anywhere inside the arena except
  # in a vertical column above a beacon/capture point.

  breakable-blocks:
    - RED_TERRACOTTA
    - BLUE_TERRACOTTA
    - RED_STAINED_GLASS
    - BLUE_STAINED_GLASS
    - GLASS
